name: backport

on:
  workflow_dispatch:

  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
    - uses: syndesisio/backport-action@v1
